name: charts_flutter
version: 0.12.0
description: Material Design charting library for flutter.
homepage: https://github.com/google/charts

publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=2.5.0'

dependencies:
  charts_common:
    git:
      url: https://github.com/MuksithMRA/charts_flutter_plus.git
      path: charts_common/
  collection: ^1.17.1
  flutter:
    sdk: flutter
  intl: ^0.19.0
  logging: ^1.0.2
  meta: ^1.1.1


dev_dependencies:
  mockito: ^5.4.0
  build_runner: ^2.3.3
  test: ^1.24.2
